#!/bin/sh /etc/rc.common
# /etc/init.d/wifi_monitor

USE_PROCD=1
START=99
STOP=10

start_service() {
    local enabled=$(uci -q get wifi_monitor.settings.enabled)
    [ "$enabled" != "1" ] && return 0

    procd_open_instance
    procd_set_param command /usr/bin/wifi_monitor.sh
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "wifi_monitor"
}

reload_service() {
    stop
    start
}
